services:
  app:
    build: .
    container_name: bot_Hitech
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      TZ: America/Sao_Paulo
    env_file:
      - .env
    command: ["python", "main.py"]

  db:
    image: postgres
    container_name: db_Bot_HiTech
    environment:
      POSTGRES_USER: "HiTech"
      POSTGRESS_DB: "DB_BOT_HiTECH"
      POSTGRES_PASSWORD: "HiTechBot2025"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
